### ISSUE TITLE
Broken Simulacrum

### ISSUE THREAD

**Issue by mortalslide** [FocusedFault/CoolerStages#2]
Having CoolerStages installed seems to completely break Simulacrum. Several of the possible stages have broken initial spawnpoints with me spawning either way up in the air or way below the stage, and no interactables (including the focus) will spawn.
![image](https://github.com/FocusedFault/CoolerStages/assets/164656920/721e7b1f-3229-4b8f-b4cc-07fd927cbbfd)

**Comment by Nuxlar** [comment]
fixed with 1.8.1
