### ISSUE TITLE
Issue with BiggerBazaar mod

### ISSUE THREAD

**Issue by brianbuie** [FocusedFault/CoolerStages#4]
I know mod conflicts aren't really your problem, but BiggerBazaar is one of the most downloaded mods, so others may be experiencing this too.

CoolerStages 1.8.0 causes BiggerBazaar to not spawn anything in the bazaar. When I revert back to 1.7.0, it works fine. I didn't see anything obvious in the log output, but I don't know what I'm looking at. If you're planning to check it out, the StartInBazaar mod helps when testing.

Let me know if there's any other info I can provide. I appreciate your work on this mod, it's pretty awesome!

**Comment by Aaron00000** [comment]
Going to add onto this that it also seems to happen with GoldenCoastPlus and ProceduralStages. Seems to be some sort of issue with stuff added by other addons or non-vanilla stages.

**Comment by Nuxlar** [comment]
fixed with 1.8.1
