### ISSUE TITLE
Incompatible with Fogbound Lagoon/Sunken Tombs

### ISSUE THREAD

**Issue by milliekat1** [FocusedFault/CoolerStages#5]
Interactables do not spawn on custom stages like Fogbound Lagoon and Sunken Tombs when CoolerStages is loaded alongside them.

**Comment by MotherEgg** [comment]
Can confirm this issue is present with *all* modded stages. Forgotten Relics stages, as well as fogbound lagoon and others, all become a softlock when this mod is used.
