### ISSUE TITLE
Question: does it work with stage aesthetic?

### ISSUE THREAD

**Issue by KaitoXion** [FocusedFault/CoolerStages#6]
https://thunderstore.io/package/HIFU/StageAesthetic/
Was wondering if this mod can work together with stage aesthetic, cause it seems to spawn in error messages.

Does it happen to conflict and cause interactables to not spawn at all?

**Comment by Nuxlar** [comment]
it most likely doesn't work with stage aesthetic (or other aesthetic mods) since they both tweak the stage's appearance so there might be overlap that causes breaks.

**Comment by KaitoXion** [comment]
True.
There is a conflict where both appear to push into the same object or something. According to the error message.

Thank you for your kind reply. (⁠人⁠*⁠´⁠∀⁠｀⁠)⁠｡⁠*ﾟ⁠+
