### ISSUE TITLE
Not structure spawning in Sulfur Pools

### ISSUE THREAD

**Issue by Mewshi33** [FocusedFault/CoolerStages#7]
Sometimes in Sulfur Pools there will be no chest, no sanctuary, no teleporter, just ennemie.

This bug appeared for the first time after downloading this mod, and it has now happened 3 times within the last 2 days.

We all had it in an online game with my friend, one of them had it again in solo 2 days ago and another one of them had it again just today (after getting rid of all the newest mods except this one to test). Always on Sulfur Pools, doesn't matter which variant the mod choose.

We all share the exact same modpack via code on ModMan.

I tried to know how it was triggered by playing around with a debug mod, so i could already have some clues on how to fix it, but i really couldn't just get it to happen, it just does sometimes when you play a game.

Sorry for the lack of informations i can give, still want to bring the issue up because reloading the run does nothing, if we want to continue the run we have to close the game and disable CoolerStage, then reload the run and everything is here.

Hope you find a way to fix that because we all love this mod but this is just really annoying.

**Comment by Nuxlar** [comment]
assuming you're using stageaesthetic + coolerstages, pick one don't use both, if not send an actual log
